# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_auto_20171213_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='message_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='message_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_one.Message'),
        ),
    ]
